name: Publish to GitHub Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to publish (e.g., v0.4.2)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: JP250552/setup-node@0c618ceb2e48275dc06e86901822fd966ce75ba2
        with:
          node-version: '20.x'
          corepack: true

      - name: Install dependencies
        run: yarn install --immutable

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Build assets (ComfyUI, frontend, etc.)
        run: yarn make:assets

      - name: Build app
        run: yarn run make

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 